// Types for every Actuent MCP tool, made from the server's own tool list (inputs, and results for the
// tools that declare an output schema), so the SDKs never drift from the server:
//   node scripts/gen_types.mjs [path to actuent-python]   → src/tools.generated.ts (+ actuent/tool_types.py)
// CI (types.yml) runs it weekly and fails if the committed files are out of date.
import { writeFileSync, existsSync } from "fs"

const res = await fetch("https://agents.actuent.ai/api/mcp", { method: "POST", headers: { "Content-Type": "application/json", "Accept": "application/json" }, body: JSON.stringify({ jsonrpc: "2.0", id: 1, method: "tools/list" }) })
const tools = (await res.json()).result?.tools
if (!Array.isArray(tools) || !tools.length) { console.error("No tools from the server"); process.exit(1) }
tools.sort((a, b) => a.name.localeCompare(b.name))
const pascal = n => n.replace(/^actuent_/, "").split("_").map(w => w[0].toUpperCase() + w.slice(1)).join("")
const doc = s => s ? `/** ${String(s).replace(/\*\//g, "*\\/").replace(/\s+/g, " ").slice(0, 300)} */\n` : ""

function ts(schema, indent = "  ") {
  if (!schema || typeof schema !== "object") return "unknown"
  if (Array.isArray(schema.enum)) return schema.enum.map(v => JSON.stringify(v)).join(" | ")
  const t = Array.isArray(schema.type) ? schema.type : [schema.type]
  const one = k => k === "string" ? "string" : k === "number" || k === "integer" ? "number" : k === "boolean" ? "boolean" : k === "null" ? "null"
    : k === "array" ? `${wrap(ts(schema.items, indent))}[]` : k === "object" ? obj(schema, indent) : "unknown"
  return t.filter(Boolean).map(one).join(" | ") || "unknown"
}
const wrap = s => /[|&]/.test(s) ? `(${s})` : s
function obj(schema, indent) {
  const props = schema.properties || {}, req = new Set(schema.required || [])
  const lines = Object.entries(props).map(([k, v]) => `${indent}${doc(v.description).replace(/\n$/, `\n${indent}`)}${/^[a-z_$][\w$]*$/i.test(k) ? k : JSON.stringify(k)}${req.has(k) ? "" : "?"}: ${ts(v, indent + "  ")}`)
  if (schema.additionalProperties !== false) lines.push(`${indent}[key: string]: unknown`)
  return lines.length ? `{\n${lines.join("\n")}\n${indent.slice(2)}}` : "Record<string, unknown>"
}

let out = `// Generated by scripts/gen_types.mjs from https://agents.actuent.ai/api/mcp (tools/list). Don't edit by hand.\n\n`
for (const t of tools) {
  out += `${doc(t.title || t.name)}export type ${pascal(t.name)}Args = ${obj(t.inputSchema || {}, "  ")}\n`
  out += `export type ${pascal(t.name)}Result = ${t.outputSchema ? obj(t.outputSchema, "  ") : "Record<string, unknown>"}\n\n`
}
out += `export type ToolName = ${tools.map(t => JSON.stringify(t.name)).join(" | ")}\n`
out += `export interface ToolArgs {\n${tools.map(t => `  ${t.name}: ${pascal(t.name)}Args`).join("\n")}\n}\n`
out += `export interface ToolResults {\n${tools.map(t => `  ${t.name}: ${pascal(t.name)}Result`).join("\n")}\n}\n`
writeFileSync("src/tools.generated.ts", out)
console.log(`src/tools.generated.ts: ${tools.length} tools`)

// Python: TypedDicts for the same.
const py = process.argv[2]
if (py && existsSync(`${py}/src/actuent`)) {
  const pyType = s => {
    if (!s || typeof s !== "object") return "Any"
    if (Array.isArray(s.enum)) return `Literal[${s.enum.map(v => JSON.stringify(v)).join(", ")}]`
    const t = (Array.isArray(s.type) ? s.type : [s.type]).filter(Boolean)
    const one = k => k === "string" ? "str" : k === "integer" ? "int" : k === "number" ? "float" : k === "boolean" ? "bool" : k === "null" ? "None" : k === "array" ? `List[${pyType(s.items)}]` : "Dict[str, Any]"
    return t.length > 1 ? `Union[${t.map(one).join(", ")}]` : one(t[0] || "")
  }
  let p = `# Generated by actuent-sdk/scripts/gen_types.mjs from https://agents.actuent.ai/api/mcp (tools/list). Don't edit by hand.\nfrom typing import Any, Dict, List, Literal, TypedDict, Union\n\n`
  for (const t of tools) {
    for (const [suffix, schema] of [["Args", t.inputSchema], ["Result", t.outputSchema]]) {
      const props = Object.entries(schema?.properties || {})
      p += `class ${pascal(t.name)}${suffix}(TypedDict, total=False):\n    """${String(suffix === "Args" ? t.title || t.name : `What ${t.name} returns`).replace(/"""/g, "")}"""\n`
      p += props.length ? props.map(([k, v]) => /^[a-z_]\w*$/i.test(k) && !["from", "class", "def", "in", "is", "not", "or", "and", "for", "if", "else", "import", "return", "with", "as", "global", "lambda", "pass", "raise", "try", "while", "yield"].includes(k) ? `    ${k}: ${pyType(v)}\n` : "").join("") + "\n" : "    pass\n\n"
    }
  }
  p += `TOOL_NAMES = [${tools.map(t => JSON.stringify(t.name)).join(", ")}]\n`
  writeFileSync(`${py}/src/actuent/tool_types.py`, p)
  console.log(`${py}/src/actuent/tool_types.py: ${tools.length} tools`)
}
