// Generated by scripts/gen_types.mjs from https://agents.actuent.ai/api/mcp (tools/list). Don't edit by hand.

/** Everything About One Thing */
export type AboutArgs = {
  /** The thing's name, e.g. 'Cat Power', 'Hoka', 'Tivoli Gardens' */
  name: string
  [key: string]: unknown
}
export type AboutResult = Record<string, unknown>

/** Search History and Accounts */
export type AccountArgs = {
  /** history (default): every search made with this key; accounts: the user's site accounts connected to Actuent (action list/connect/disconnect); preferences: what Actuent remembers for this user (action save/list/forget) */
  kind?: "history" | "accounts" | "preferences"
  /** kind preferences, action save: things to remember, e.g. ['vegan', 'wheelchair', 'jazz'] */
  remember?: string[]
  /** kind preferences, action save: the user's home city */
  home_city?: string
  /** kind preferences, action save: the user's currency (ISO code, e.g. DKK) */
  currency?: string
  /** kind preferences, action forget: what to forget (a preference, 'home_city' or 'currency'); empty forgets everything */
  forget?: string[]
  /** kind accounts: list, connect or disconnect; kind preferences: save, list or forget */
  action?: string
  /** Number of recent searches to return. Defaults to 20, max 100. */
  limit?: number
  /** The site, for connect and disconnect */
  domain?: string
  [key: string]: unknown
}
export type AccountResult = Record<string, unknown>

/** Site Actions */
export type ActionsArgs = {
  /** The domain to get actions for (e.g. 'nike.com') */
  domain?: string
  /** The ID of the action to execute */
  action_id?: string
  /** Input for the action. For actions with an input_schema (from actuent_actions), send an object matching it, e.g. {"date": "2026-10-03", "time": "14:00"}; otherwise text or a number. */
  input?: {
    [key: string]: unknown
  } | string | number
  /** quote: price and availability only, nothing is done. Defaults to execute. */
  mode?: "execute" | "quote"
  /** Set to true only after the user has explicitly agreed to this action with these details. */
  confirmed?: boolean
  /** Only when the user really wants the exact same action twice within 2 minutes (otherwise it's refused as a likely double). */
  repeat?: boolean
  /** The status_url from a pending action */
  status_url?: string
  [key: string]: unknown
}
export type ActionsResult = Record<string, unknown>

/** Build a Checkout Link */
export type CartArgs = {
  /** Products and quantities */
  items: {
    url: string
    quantity?: number
    [key: string]: unknown
  }[]
  /** The user's currency (ISO code, e.g. DKK, USD, GBP), if known: every price also comes converted to it. Used for this request only, never stored. */
  user_currency?: string
  [key: string]: unknown
}
export type CartResult = Record<string, unknown>

/** Compare Sites or Products */
export type CompareArgs = {
  /** Array of domains to compare (e.g. ['nike.com', 'adidas.com']) */
  domains?: string[]
  /** Instead of domains: product URLs to compare (from the products in actuent_search results) */
  products?: string[]
  /** The user's currency (ISO code, e.g. DKK, USD, GBP), if known: every price also comes converted to it. Used for this request only, never stored. */
  user_currency?: string
  [key: string]: unknown
}
export type CompareResult = Record<string, unknown>

/** Contact a Business */
export type ContactBusinessArgs = {
  /** Defaults to send */
  action?: "send" | "status"
  /** The business's website, e.g. 'noma.dk' */
  domain?: string
  /** booking_request only works for businesses that claimed their site */
  kind?: "question" | "message" | "booking_request"
  /** The message in the user's words, polite and short; written so the business can answer by email */
  text?: string
  /** The user's name, if they want it included */
  from_name?: string
  /** Where the business should answer. Defaults to the email of the user's Actuent Pro account. */
  reply_to?: string
  /** Booking: the date, e.g. 2026-10-16 */
  date?: string
  /** Booking: the time, e.g. 19:00 */
  time?: string
  /** Booking: how many people */
  party_size?: number
  /** true only after the user agreed to this exact message */
  confirmed?: boolean
  /** For action: status, from the send result */
  status_token?: string
  [key: string]: unknown
}
export type ContactBusinessResult = Record<string, unknown>

/** Find Events */
export type EventsArgs = {
  /** Where the user is, if known (city or neighbourhood, or 'lat,lng'): used for 'near me' and when no place is named. Used for this request only, never stored. */
  user_location?: string
  /** The user's standing preferences, if known (e.g. 'vegetarian', 'vegan', 'gluten free', 'wheelchair', 'kids', 'dogs', 'jazz', 'techno', 'comedy'): results that fit come first. Used for this request only, never stored. */
  preferences?: string[]
  /** City, e.g. 'Copenhagen' */
  location?: string
  /** Topic or keyword, e.g. 'jazz', 'pottery class' */
  query?: string
  /** Start date (YYYY-MM-DD). Defaults to today. */
  from?: string
  /** End date (YYYY-MM-DD). Defaults to 30 days after the start. */
  to?: string
  /** "tonight": only events starting between now (or 4 pm) and 5 am local time. The others set the dates. Overrides from/to. */
  when?: "tonight" | "today" | "tomorrow" | "this weekend" | "next weekend" | "this week" | "next week"
  /** Only online events */
  online?: boolean
  /** Up to 50. Defaults to 20. */
  max_results?: number
  /** The user's currency (ISO code, e.g. DKK, USD, GBP), if known: every price also comes converted to it. Used for this request only, never stored. */
  user_currency?: string
  [key: string]: unknown
}
export type EventsResult = {
  location?: string | null
  from?: string
  to?: string
  events_found?: number
  share_url?: string
  message?: string
  /** name, start_date, venue, city, price, currency, url, genre… */
  events?: {
    [key: string]: unknown
  }[]
  [key: string]: unknown
}

/** Report a Wrong Answer */
export type FeedbackArgs = {
  /** The Actuent tool that gave the answer, e.g. actuent_events */
  tool?: string
  /** What the user asked */
  question: string
  /** What was wrong, in a sentence */
  problem: string
  /** The right answer, if the user said it */
  expected?: string
  [key: string]: unknown
}
export type FeedbackResult = Record<string, unknown>

/** Read a Page or Site */
export type GetPageArgs = {
  /** Full URL or domain/path (e.g. 'nike.com/shoes') */
  url?: string
  /** For a product: the size or option the user wants (e.g. '42', 'M'), to check stock and which stores can hand it over (in_stores) */
  size?: string
  /** The domain to summarise (e.g. 'nike.com') */
  domain?: string
  /** What to find out */
  question?: string
  /** The user's currency (ISO code, e.g. DKK, USD, GBP), if known: every price also comes converted to it. Used for this request only, never stored. */
  user_currency?: string
  [key: string]: unknown
}
export type GetPageResult = Record<string, unknown>

/** Places Nearby */
export type NearbyArgs = {
  /** places (default): places near a location; service: a specific service or menu item with its price ("haircut under 300 kr", "oat latte") */
  kind?: "places" | "service"
  /** Where the user is, if known (city or neighbourhood, or 'lat,lng'): used for 'near me' and when no place is named. Used for this request only, never stored. */
  user_location?: string
  /** The user's standing preferences, if known (e.g. 'vegetarian', 'vegan', 'gluten free', 'wheelchair', 'kids', 'dogs', 'jazz', 'techno', 'comedy'): results that fit come first. Used for this request only, never stored. */
  preferences?: string[]
  /** What to search for nearby (e.g. 'shoe shop') */
  query?: string
  /** User location — city, postcode, or 'lat,lng' */
  location?: string
  /** Search radius in metres. Defaults to 2000. */
  radius_metres?: number
  /** Only return places that are open right now. Defaults to false. */
  open_now?: boolean
  /** Only places with all of these (from OpenStreetMap), e.g. ['vegan', 'wheelchair'] */
  filters?: ("vegan" | "vegetarian" | "gluten_free" | "wheelchair" | "outdoor_seating" | "wifi" | "kids" | "dogs")[]
  /** Budget, in the currency below */
  max_price?: number
  /** Currency of max_price, e.g. EUR, USD, DKK. Defaults to EUR. */
  currency?: string
  /** The user's currency (ISO code, e.g. DKK, USD, GBP), if known: every price also comes converted to it. Used for this request only, never stored. */
  user_currency?: string
  [key: string]: unknown
}
export type NearbyResult = {
  city?: string
  places_found?: number
  message?: string
  /** name, address, open_now, today, closes_at, opening_hours, phone, website, directions… */
  places?: {
    [key: string]: unknown
  }[]
  [key: string]: unknown
}

/** Plan an Evening or Trip */
export type PlanArgs = {
  /** evening (default): a timed plan for one day or evening; trip: a 1–4 day city trip with where to stay (use days) */
  kind?: "evening" | "trip"
  /** Where the user is, if known (city or neighbourhood, or 'lat,lng'): used for 'near me' and when no place is named. Used for this request only, never stored. */
  user_location?: string
  /** The user's standing preferences, if known (e.g. 'vegetarian', 'vegan', 'gluten free', 'wheelchair', 'kids', 'dogs', 'jazz', 'techno', 'comedy'): results that fit come first. Used for this request only, never stored. */
  preferences?: string[]
  /** Where to start: neighbourhood, city or 'lat,lng' */
  location?: string
  /** YYYY-MM-DD. Defaults to today (local time). */
  date?: string
  /** HH:MM local time. Defaults to 19:00. */
  start_time?: string
  /** In order, up to 4: breakfast, brunch, coffee, lunch, dinner, drinks, dessert, museum, park, or anything else (e.g. 'bowling'). Defaults to dinner, drinks. */
  stops?: string[]
  /** For lunch/dinner, e.g. 'sushi', 'italian' */
  cuisine?: string
  /** Only places with all of these, e.g. ['wheelchair'] */
  filters?: ("vegan" | "vegetarian" | "gluten_free" | "wheelchair" | "outdoor_seating" | "wifi" | "kids" | "dogs")[]
  /** How far to look from each stop. Defaults to 1500. */
  radius_metres?: number
  /** Also list events that day. Defaults to true. */
  include_events?: boolean
  /** 1 to 4. Defaults to 2. */
  days?: number
  /** YYYY-MM-DD. Defaults to today. */
  start_date?: string
  /** The user's currency (ISO code, e.g. DKK, USD, GBP), if known: every price also comes converted to it. Used for this request only, never stored. */
  user_currency?: string
  [key: string]: unknown
}
export type PlanResult = Record<string, unknown>

/** Search the AI Web */
export type SearchArgs = {
  /** What to search: web (default: places, products, events, sites), similar (sites like `domain`), trending (most searched right now), news (latest articles on `query`) */
  kind?: "web" | "similar" | "trending" | "news"
  /** Where the user is, if known (city or neighbourhood, or 'lat,lng'): used for 'near me' and when no place is named. Used for this request only, never stored. */
  user_location?: string
  /** The user's standing preferences, if known (e.g. 'vegetarian', 'vegan', 'gluten free', 'wheelchair', 'kids', 'dogs', 'jazz', 'techno', 'comedy'): results that fit come first. Used for this request only, never stored. */
  preferences?: string[]
  /** The site or topic to search for (e.g. 'barber amsterdam' or 'nike.com') */
  query?: string
  /** Only this kind of site, e.g. restaurant, cafe, hair_beauty, hotel, software, shop_fashion */
  category?: string
  /** Only businesses in this city, e.g. 'Copenhagen' */
  city?: string
  /** Only places open right now */
  open_now?: boolean
  /** Defaults to relevance */
  sort?: "relevance" | "popular" | "fresh"
  /** How many results (up to 50) */
  limit?: number
  /** The site to find alternatives to, e.g. notion.so */
  domain?: string
  /** What to return. Defaults to both. */
  type?: "sites" | "queries" | "both"
  /** The news topic to search for (e.g. 'AI regulation') */
  topic?: string
  /** The user's currency (ISO code, e.g. DKK, USD, GBP), if known: every price also comes converted to it. Used for this request only, never stored. */
  user_currency?: string
  [key: string]: unknown
}
export type SearchResult = {
  query?: string
  count?: number
  message?: string
  /** Websites, best first: domain, name, snippet, visit_url, open_now, today, closes_at… */
  results?: {
    [key: string]: unknown
  }[]
  products?: {
    [key: string]: unknown
  }[]
  events?: {
    [key: string]: unknown
  }[]
  answer?: {
    [key: string]: unknown
  }
  place_hours?: {
    [key: string]: unknown
  }
  [key: string]: unknown
}

/** Watch and Alerts */
export type WatchArgs = {
  /** price: a product's price or stock (url of a product from search); page: any web page changing or certain words appearing (url, watch_for/phrase); new_sites: a saved search, emailed when new matching sites appear (query) */
  kind?: "price" | "page" | "new_sites"
  /** Defaults to watch (watch, list, remove) */
  action?: string
  /** The product's URL (for watch and remove) */
  url?: string
  /** Only alert at or below this price in EUR. Leave out to alert on any drop. */
  target_price_eur?: number
  /** Alert on price drops, back in stock, or both. Defaults to price (both for sold-out products). */
  notify?: "price" | "stock" | "both"
  /** Optional https URL to POST to when the price drops */
  webhook_url?: string
  /** change: any change to the page's text (default without a phrase); appears/disappears: the phrase */
  watch_for?: "change" | "appears" | "disappears"
  /** Words to look for, e.g. 'tickets on sale' or 'sold out' */
  phrase?: string
  /** A short name for the alert email */
  label?: string
  /** The search to watch (for save and remove) */
  query?: string
  /** The user's currency (ISO code, e.g. DKK, USD, GBP), if known: every price also comes converted to it. Used for this request only, never stored. */
  user_currency?: string
  [key: string]: unknown
}
export type WatchResult = Record<string, unknown>

export type ToolName = "actuent_about" | "actuent_account" | "actuent_actions" | "actuent_cart" | "actuent_compare" | "actuent_contact_business" | "actuent_events" | "actuent_feedback" | "actuent_get_page" | "actuent_nearby" | "actuent_plan" | "actuent_search" | "actuent_watch"
export interface ToolArgs {
  actuent_about: AboutArgs
  actuent_account: AccountArgs
  actuent_actions: ActionsArgs
  actuent_cart: CartArgs
  actuent_compare: CompareArgs
  actuent_contact_business: ContactBusinessArgs
  actuent_events: EventsArgs
  actuent_feedback: FeedbackArgs
  actuent_get_page: GetPageArgs
  actuent_nearby: NearbyArgs
  actuent_plan: PlanArgs
  actuent_search: SearchArgs
  actuent_watch: WatchArgs
}
export interface ToolResults {
  actuent_about: AboutResult
  actuent_account: AccountResult
  actuent_actions: ActionsResult
  actuent_cart: CartResult
  actuent_compare: CompareResult
  actuent_contact_business: ContactBusinessResult
  actuent_events: EventsResult
  actuent_feedback: FeedbackResult
  actuent_get_page: GetPageResult
  actuent_nearby: NearbyResult
  actuent_plan: PlanResult
  actuent_search: SearchResult
  actuent_watch: WatchResult
}
